site_name: Zhiyuan Chen
site_url: https://zc.int.xyz
site_author: Zhiyuan Chen
site_description: The website of Zhiyuan Chen
copyright: All rights reserved © Zhiyuan Chen 2019

repo_name: The website of Zhiyuan Chen
repo_url: https://github.com/yc-zc/web

nav:
  - 首页: index.md
  - 捐赠: master/donate.md
  - 关于: master/about.md
  - 简历: master/curriculum_vitae.md
  - Resume: master/resume.md
  # - 联想研究院:
  #   - 联想研究院实习总结: lenovo_research.md
  - 文档:
    - JetBrains使用指南: document/jetbrains.md
  - 算法:
    - 算法导论: algorithm/introduction.md
    - 复杂度: algorithm/complexity.md
  - Kubernetes:
    - 导论: kubernetes/introduction.md
    - 安装: kubernetes/installation.md
    - Pods: kubernetes/pods.md
    - Deployments: kubernetes/deployments.md
  - Docker:
    - 导论: docker/introduction.md
    - 安装: docker/installation.md
    - 命令行接口: docker/command_line_interface.md
    - Dockerfile: docker/dockerfile.md
  - CNTK:
    - 导论: cntk/introduction.md
    - 200: cntk/200.md
  - C++核心指南:
    - 原文: CppCoreGuidelines/CppCoreGuidelines.md
    - 摘要: CppCoreGuidelines/abstract.md
  - 随笔:
    - 二〇一九年 六月 十日: sketch/20190610.md
    - 二〇一九年 六月 十九日: sketch/20190619.md
    - 二〇一九年 七月 二十七日: sketch/20190727.md
  
theme:
  name: material
  palette:
    primary: 'teal'
    accent: 'teal'
  logo: 'images/zc.png'
  favicon: 'images/favicon.ico'
  feature:
    tabs: true

extra:
  manifest: 'manifest.webmanifest'
  social:
    - type: 'github'
      link: 'https://github.com/int-zc'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/in/%E9%99%9F%E5%8E%9F-%E9%99%88-0b473aa9/'
  disqus: 'intzc'

extra_css:
    - css/css.css
    - css/extra.css

extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

google_analytics:
  - 'UA-104387513-1'
  - 'auto'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      use_pygments: True
      noclasses: True
      pygments_style: monokai
  - def_list
  - footnotes
  - meta
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: "#"
  - mdx_math

plugins:
  - search
  - awesome-pages
  # - git-committers