site_name: Zhiyuan Chen
site_url: https://zyc.ai
site_author: Zhiyuan Chen
site_description: The website of Zhiyuan Chen
copyright: All rights reserved © Zhiyuan Chen 2017-2020

repo_name: Zhiyuan Chen
repo_url: https://github.com/zyc-ai

nav:
  - zyc.ai: index.md
  # - 联想研究院:
  #   - 联想研究院实习总结: lenovo_research.md
  - 文档:
    - 设计模式: document/design_pattern.md
    - JetBrains使用指南: document/jetbrains.md
  - 统计:
    - 概率论: stat/probability.md
  #- 机器学习:
  #  - 统计: ml/statistics.md
  #- 计算机视觉:
  #  - SiamRPN: cv/siamrpn.md
  # - 生物医学影像:
  #   - 超声: bmi/ultrasound.md
  - 算法:
    - 算法导论: algorithm/introduction.md
    - 复杂度: algorithm/complexity.md
    - 树: algorithm/tree.md
    - 递推方程: algorithm/recurrence_relation.md
  - Kubernetes:
    - 导论: k8s/introduction.md
    - 组件: k8s/component.md
    - 安装: k8s/installation.md
    - Pods: k8s/pods.md
    - Deployments: k8s/deployments.md
  - Docker:
    - 导论: docker/introduction.md
    - 安装: docker/installation.md
    - 命令行接口: docker/command_line_interface.md
    - Dockerfile: docker/dockerfile.md
  - CNTK:
    - 导论: cntk/introduction.md
    - 200: cntk/200.md
  - C++核心指南:
    - 原文: cppcg/CppCoreGuidelines.md
    - 摘要: cppcg/abstract.md
  - 随笔:
    - 二〇一九年 六月 十日: sketch/20190610.md
    - 二〇一九年 十一月 八日: sketch/20191108.md
    - 二〇二〇年 四月 四日: sketch/20200404.md
  - 关于:
    - 捐赠: about/donate.md
    - 贡献: about/contribute.md
    - 最终用户许可协议: about/eula.md
    - 隐私声明: about/privacy.md
    - 评论政策: about/comment.md
    - GPLv3: about/license.md
    - Zhiyuan Chen: about/zhiyuan_chen.md

icon:
  logo: 'images/zc.png'

theme:
  name: material
  language: 'zh'
  palette:
    scheme: slate
    primary: 'Teal'
    accent: 'Teal'
  logo: 'images/zc.png'
  favicon: 'favicon.ico'
  feature:
    - tabs
    - instant
  font:
    text: 'Noto Sans'
    code: 'Cascadia Code'

extra:
  manifest: 'manifest.webmanifest'
  social:
    - icon: fontawesome/brands/github-alt
      link: 'https://github.com/zyc-ai'
    # - icon: 'linkedin'
    #   link: 'https://www.linkedin.com/in/%E9%99%9F%E5%8E%9F-%E9%99%88-0b473aa9/'
  disqus: 'intzc'

extra_css:
    - css/css.css
    #- css/extra.css

extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

google_analytics:
  - 'UA-104387513-1'
  - 'auto'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      use_pygments: True
      noclasses: True
      pygments_style: monokai
  - def_list
  - footnotes
  - mdx_math
  - meta
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: "#"

plugins:
  - search:
      separator: '[\s\-\.]+'
      lang:
        - en
  - awesome-pages
  # - git-committers